### ISSUE TITLE
Stekjes -detailpage component

### ISSUE THREAD

**Issue by YoussraElmortai** [TimOosterveer/back-to-static-plantswap#18]
Is het component responsive?
 
- [x] Big screen
- [x] Middle screen
- [x] Small screen
 
Is het component toegankelijk
 
- [x] Tab test 
- [x] Lighthouse test
- [x] Contrast test
 
Is het component performant
 
- [x] Alle plaatjes nog comprimeren
- [x] Images sizes staan in de html
- [x] Images laoding lazy

**Comment by iBadr49** [comment]
Tijdens de device test wil ik de volgende testen:

**Tester is Stefan**

Responsive ontwerp:
`De gebruiker kan op elk device de pagina workshops bezoeken: mobile, tablet en laptop/desktop
`

Feedback/Review : Pagina is responsive.

Tab toets:
`De gebruiker moet met de tab toets door de pagina heen!


Feedback/Review:  Verander je accordion -code zodat je met de tab de accordion open en dicht kan klappen ..

**Comment by iBadr49** [comment]
Ik heb de code aangepast en alle bugs zijn nu ge-fixt
