### ISSUE TITLE
header component

### ISSUE THREAD

**Issue by YoussraElmortai** [TimOosterveer/back-to-static-plantswap#22]
Is het component responsive?
 
- [x] Big screen
- [x] Middle screen
- [x] Small screen
 
Is het component toegankelijk
 
- [x] Tab test 
- [x] Lighthouse test
- [x] Contrast test
 
Is het component performant
 
- [x] Alle plaatjes nog comprimeren
- [x] Images sizes staan in de html
- [x] Images laoding lazy

**Comment by iBadr49** [comment]
![Image](https://github.com/TimOosterveer/back-to-static-plantswap/assets/112857932/92357b3b-a750-47ad-8ad7-def2fb60b916)
